defaultPortal: dev
portals:
  # Sample apikey entry, manually entered
  - name: AA Autoarti Demo Account
    portalId: 20290505
    defaultMode: 'publish'
    authType: apikey
    apiKey:  ${{ secrets.HAPIKEY }}
